input {
  file {
    path => ["/logs/auth.jsonl"]
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/ssh.sincedb"
    codec => json { ecs_compatibility => "disabled" }
    ecs_compatibility => "disabled"
    stat_interval => "1 second"
  }
}
filter {
  if [message] =~ /^(Failed|Accepted) password for / {
    grok {
      match => { "message" => "^%{WORD:[@metadata][result]} password for (?:invalid user )?%{NOTSPACE:[user][name]} from %{IP:[source][ip]} port %{POSINT:[source][port]:int} ssh2(?:.*)?$" }
    }
    if "_grokparsefailure" not in [tags] {
      mutate { add_field => { "[event][category]" => "authentication" } }
      if [@metadata][result] == "Failed" {
        mutate { add_field => { "[event][outcome]" => "failure" } }
      } else {
        mutate { add_field => { "[event][outcome]" => "success" } }
      }
    }
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "mini-siem-logs"
    document_id => "%{[event][id]}"
    manage_template => false
    ilm_enabled => false
    data_stream => false
  }
}
